"""Add openai_api_key

Revision ID: c7209f9431e5
Revises: f4e16d3fbe12
Create Date: 2026-01-27 04:43:38.033410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7209f9431e5'
down_revision: Union[str, None] = 'f4e16d3fbe12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
